apiVersion: v1
kind: Service
metadata: # kpt-merge: nginx/my-nginx-svc
  name: my-nginx-svc
  labels:
    app: nginx
    app.kubernetes.io/name: app
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|nginx|my-nginx-svc'
  namespace: nginx
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  externalTrafficPolicy: Cluster
