# fn-config.yaml
apiVersion: fn.kpt.dev/v1alpha1
kind: SetImage
metadata: # kpt-merge: /set-image
  name: set-image
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|SetImage|default|set-image'
image:
  name: bitnami/nginx
  newName: nginx
  newTag: latest
